### ISSUE TITLE
Generate Pooling / Google Forms for Date and Topics definition

### ISSUE THREAD

**Issue by rikatz** [Cloud-Native-BR/kcd-sp#1]
Generate a pool / Google Forms to verify with the community;

* Would they attend an event on Saturday or a work day is prefered?
* Which topics is there more interest so we can build the tracks

* Define a deadline for this Form

**Comment by wagnerbianchijr** [comment]
Hey, @rikatz! Is it for adding a preferred weekday here, or you're going to set another medium to collect answers like a poll somewhere?

**Comment by rikatz** [comment]
Hi @wagnerbianchijr tks for your interest. 

This issue was opened to register that @duboc needs to generate a pool and post the medium, so We can publish and spread it over all social media and gather information whether the community will participate in a weekend or not :)

Tks!

**Comment by jhonatanmorais** [comment]
> Hey, @rikatz! Is it for adding a preferred weekday here, or you're going to set another medium to collect answers like a poll somewhere?

@wagnerbianchijr We'll create a Google Forms poll with some questions to share with the community on Twitter and Telegram.

**Comment by duboc** [comment]
Form is done. We should run this survey until Feb, 2020. 

http://bit.ly/kcdsaopaulo

Results will be public available at the end of the Poll.
