### ISSUE TITLE
Recurring meeting schedule

### ISSUE THREAD

**Issue by rikatz** [Cloud-Native-BR/kcd-sp#2]
We need to define a recurring meeting schedule.

Let's put the the suggestions here and consolidate the best week day, hour and within each days for our recurring meeting.

Due answers: 18/Dec/2019

**Comment by rikatz** [comment]
What works for me:

* Recurring meeting by 15 days
* Best week days: Tuesday or Wednesday 6pm or 7pm
Those meetings might be also during the day (like starting at 2pm) but can't guarantee I won't have an agenda conflict with my job

**Comment by jhonatanmorais** [comment]
Recurring meeting by 15 days
Best week days: Tuesday or Wednesday, 7pm or 8pm (or later)

**Comment by yagonobre** [comment]
Please ignore the dates, just consider the weekday.

https://doodle.com/poll/v3irgm96n4e74xu7

**Comment by rikatz** [comment]
Bi weekly for me also, filled the Doodle here

**Comment by yagonobre** [comment]
I'll send the invite at EOD

**Comment by duboc** [comment]
Bi weekly for me too. 

Tuesdays or Wednesday after 7pm works for me.

**Comment by yagonobre** [comment]
It'll be Tuesdays at 9pm, sending the invite!
