### ISSUE TITLE
Provide a swag company contact to gather pricing

### ISSUE THREAD

**Issue by rikatz** [Cloud-Native-BR/kcd-sp#5]
Provide a trustable swag company so We can gather pricing and put it into the finances.

**Comment by duboc** [comment]
@jhonatanmorais is talking to several companies and the one I recommended is hsmerch.: https://www.hsmerch.com/

**Comment by rikatz** [comment]
> @jhonatanmorais is talking to several companies and the one I recommended is hsmerch.: https://www.hsmerch.com/

They have nice Bad Religion and Dropkick Murphys swags also :P 

@jhonatanmorais I can provide some help with this subject, if you need it. Take a ride into Bras or somewhere else to have some ideas and pricing also, or maybe call those companies you've provided

@duboc tks!
