### ISSUE TITLE
Make contact with financial support agencies

### ISSUE THREAD

**Issue by rikatz** [Cloud-Native-BR/kcd-sp#8]
We need to find a company that can issue the invoices and deal with the financial part and money flow.

Some, but not limited attributions of this company will be:

* Receive sponsorship money and issue invoices
* Make a final financial report of the event
* Deal with other financial issues

**Comment by rikatz** [comment]
One of the suggested companies by Leandro from C4Media was Alua Eventos: http://aluaeventos.com.br/

**Comment by yagonobre** [comment]
We also have Altos and Boutique 08. I'll send a mail to everyone.

**Comment by rikatz** [comment]
@yagonobre ping
